{
 "title": "New dashboard12",
 "time": { "from": "2024-01-03T02:30:02.969Z", "to": "2024-01-03T03:18:07.060Z" },
 "panels": [
  {
   "title": "sirius_deps_latency_seconds_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sirius_deps_latency_seconds_bucket",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sirius_deps_latency_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sirius_deps_latency_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sirius_deps_latency_seconds_created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sirius_deps_latency_seconds_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sirius_deps_latency_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sirius_deps_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}