"""Initial tables

Revision ID: 325d401c15fe
Revises: 
Create Date: 2024-01-09 18:17:16.532873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid
# revision identifiers, used by Alembic.
revision = '325d401c15fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    product_table = op.create_table(
        'product',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False, primary_key=True, default=uuid.uuid4),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('price', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
        sa.UniqueConstraint('name', name=op.f('uq_product_name')),
        schema='public'
    )

    products = [
        {"name": "Milk", "description": "Dairy product", "price": 1.5},
        {"name": "Bread", "description": "Freshly baked bread", "price": 2.0},
        {"name": "Eggs", "description": "Organic eggs", "price": 3.0},
        {"name": "Cheese", "description": "Assorted cheese", "price": 4.5},
        {"name": "Apples", "description": "Crispy red apples", "price": 1.0},
        {"name": "Chicken", "description": "Free-range chicken", "price": 5.0},
        {"name": "Tomatoes", "description": "Vine-ripened tomatoes", "price": 2.5},
        {"name": "Pasta", "description": "Italian pasta", "price": 1.8},
        {"name": "Coffee", "description": "Premium coffee beans", "price": 6.0},
        {"name": "Orange Juice", "description": "Freshly squeezed orange juice", "price": 3.5},
    ]

    op.bulk_insert(product_table, products)
    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username')),
    schema='public'
    )
    op.create_table('order',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.id'], name=op.f('fk_order_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order')),
    schema='public'
    )
    op.create_table('order_product',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['public.order.id'], name=op.f('fk_order_product_order_id_order')),
    sa.ForeignKeyConstraint(['product_id'], ['public.product.id'], name=op.f('fk_order_product_product_id_product')),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name=op.f('pk_order_product')),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_product', schema='public')
    op.drop_table('order', schema='public')
    op.drop_table('user', schema='public')
    op.drop_table('product', schema='public')
    # ### end Alembic commands ###
