"""Добавлен статус для заказа

Revision ID: 801f71d901c7
Revises: 325d401c15fe
Create Date: 2024-01-11 13:10:42.090229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801f71d901c7'
down_revision = '325d401c15fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.Text(), nullable=False))
    op.drop_constraint('fk_order_user_id_user', 'order', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_user_id_user'), 'order', 'user', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('fk_order_product_order_id_order', 'order_product', type_='foreignkey')
    op.drop_constraint('fk_order_product_product_id_product', 'order_product', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_product_product_id_product'), 'order_product', 'product', ['product_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(op.f('fk_order_product_order_id_order'), 'order_product', 'order', ['order_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_order_product_order_id_order'), 'order_product', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_product_product_id_product'), 'order_product', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_order_product_product_id_product', 'order_product', 'product', ['product_id'], ['id'])
    op.create_foreign_key('fk_order_product_order_id_order', 'order_product', 'order', ['order_id'], ['id'])
    op.drop_constraint(op.f('fk_order_user_id_user'), 'order', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_order_user_id_user', 'order', 'user', ['user_id'], ['id'])
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
