{
 "title": "Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "INTEGRATIONS_LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(sirius_integrations_latency_seconds_bucket[1m])) by (le, integration))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REQUEST_COUNT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_errors_total) by (method, endpoint, http_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REQUEST_COUNT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (method, endpoint, http_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ROUTES_LATENCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(sirius_routes_latency_seconds_bucket[1m])) by (le, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}